### PR TITLE
Relink URL's

### LINKED ISSUE #101: GH Pages backrouting to old repo
**Is your question related to a problem? Please describe.**
The Github Page is linking to old downloads

**Describe the question you have.**
Is this intentional?

**Additional context**
If not, can someone try relinking it?

### PR DESCRIPTION
**Pull request by StoppedwummSites**
Relinked URL's to actual repo, so people don't get confused with the old one

Fixes #101

### CODE REVIEW

**Comment by StoppedwummSites** [comment]
Fixes #101

**Comment by StoppedwummSites** [comment]
- [ ] Remake the HTML Links
- [ ] Maybe change email?
- [ ] Info that this is a fork

**Comment by Stoppedwumm** [comment]
@StefanLobbenmeier

**Comment by StefanLobbenmeier** [comment]
Thanks ❤️ I already changed most of the URLs, but looks like I missed that one

**Pull request merged**
