### PR TITLE
Reload limiter setting

### PR DESCRIPTION
**Pull request by jeronimo**
This was tested only on macOS and was added because of very intermittent and throttled down Starlink internet.

### CODE REVIEW

**Comment by StefanLobbenmeier** [comment]
Thanks for the contribution. Code changes look good to me on my phone, I will test it later too. 

The package-lock.json looks a bit scary to me, I think I will regenerate it and check that it’s the same result on my machine

**Review by StefanLobbenmeier — APPROVED** [review]

**Comment by StefanLobbenmeier** [comment]
Also tested on my machine and confirmed that it still works as before.

**Comment by StefanLobbenmeier** [comment]
I had to revert electron-builder again, unfortunately the versions are quite hard to upgrade. But there should be a new release with your changes soon.

**Comment by StefanLobbenmeier** [comment]
https://github.com/StefanLobbenmeier/youtube-dl-gui/releases/tag/v2.4.9

**Comment by jeronimo** [comment]
Sorry about that, didn't know what were the best practices on committing modified package-lock.json

**Pull request merged**
